# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "torchbenchmark training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
enable_tensorboard = false
save_tb_folder = "tb"

[model]
# name = "resnet50""llava"
name = "resnet152"

[training]
batch_size = 960
max_norm = 1.0  # grad norm clipping
steps = 10
data_parallel_degree = -1
compile = true

[experimental]
torch_spmd = false

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
