# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "torchbenchmark training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
enable_tensorboard = false
save_tb_folder = "tb"

[model]
# name = "resnet50"
name = "hf_GPT2"

[training]
batch_size = 8
max_norm = 1.0  # grad norm clipping
steps = 10
data_parallel_degree = -1
compile = true
mixed_precision_param = "bfloat16"
mixed_precision_reduce = "bfloat16"
# mixed_precision_param = "float32"
# mixed_precision_reduce = "float32"

[experimental]
torch_spmd = true

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
